from __future__ import annotations

import json
from pathlib import Path

from . import LABELS
from .io import file_sha256


_REASON = {
    "urgent_action_request": "URGENT_ACTION_REQUEST",
    "credential_request": "CREDENTIAL_REQUEST",
    "payment_request": "PAYMENT_REQUEST",
    "private_key_request": "PRIVATE_KEY_REQUEST",
}


def export_kotlin(model_path: Path, output_path: Path) -> None:
    model = json.loads(model_path.read_text(encoding="utf-8"))
    embedding = model["embedding"]
    dimensions = int(embedding["dimensions"])

    lines = [
        "package com.cbgm.sparrow.feature.safety.data.classifier",
        "",
        "import com.cbgm.sparrow.feature.safety.domain.model.MessageSafetyReason",
        "",
        "/** Generated by tools/safety-training. Do not edit by hand. */",
        "internal object GeneratedMessageSafetyLinearModel {",
        f"    const val EMBEDDING_DIMENSIONS = {dimensions}",
        f"    const val EMBEDDING_MODEL_ID = \"{_escape(str(embedding.get('model_id') or embedding.get('model_file') or 'embedding_gemma'))}\"",
        f"    const val EMBEDDING_INPUT_MODE = \"{_escape(str(embedding['input_mode']))}\"",
        f"    const val MODEL_ARTIFACT_SHA256 = \"{file_sha256(model_path)}\"",
        f"    const val TRAINING_DATASET_SHA256 = \"{_escape(str(model.get('dataset_sha256', '')))}\"",
        *([f"    const val EMBEDDING_MODEL_SHA256 = \"{_escape(str(embedding.get('model_sha256')))}\""] if embedding.get("model_sha256") else []),
        *([f"    const val EMBEDDING_MODEL_REVISION = \"{_escape(str(embedding.get('model_revision')))}\""] if embedding.get("model_revision") else []),
        "",
        "    data class Head(",
        "        val weights: FloatArray,",
        "        val bias: Float,",
        "        val threshold: Float",
        "    )",
        "",
        "    val byReason: Map<MessageSafetyReason, Head> =",
        "        mapOf(",
    ]

    for label in LABELS:
        entry = model["labels"][label]
        weights = [float(value) for value in entry["weights"]]
        if len(weights) != dimensions:
            raise ValueError(f"{label} has {len(weights)} weights; expected {dimensions}")
        lines.extend(
            [
                f"            MessageSafetyReason.{_REASON[label]} to",
                "                Head(",
                "                    weights =",
                "                        floatArrayOf(",
            ]
        )
        for chunk_start in range(0, len(weights), 6):
            chunk = weights[chunk_start : chunk_start + 6]
            suffix = "," if chunk_start + 6 < len(weights) else ""
            lines.append("                            " + ", ".join(_float(value) for value in chunk) + suffix)
        lines.extend(
            [
                "                        ),",
                f"                    bias = {_float(float(entry['bias']))},",
                f"                    threshold = {_float(float(entry['threshold']))}",
                "                ),",
            ]
        )

    lines.extend(["        )", "}", ""])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def _float(value: float) -> str:
    return f"{value:.9g}f"


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
