from __future__ import annotations

import json
from pathlib import Path

from . import LABELS
from .io import file_sha256


_REASON = {
    "urgent_action_request": "URGENT_ACTION_REQUEST",
    "credential_request": "CREDENTIAL_REQUEST",
    "payment_request": "PAYMENT_REQUEST",
    "private_key_request": "PRIVATE_KEY_REQUEST",
}


def export_kotlin(model_path: Path, output_path: Path) -> None:
    model = json.loads(model_path.read_text(encoding="utf-8"))
    if model.get("classifier_type") != "one_vs_rest_mlp":
        raise ValueError(f"Unsupported classifier_type for Kotlin export: {model.get('classifier_type')!r}")
    embedding = model["embedding"]
    dimensions = int(embedding["dimensions"])

    lines = [
        "package com.cbgm.sparrow.feature.safety.data.classifier",
        "",
        "import com.cbgm.sparrow.feature.safety.domain.model.MessageSafetyReason",
        "",
        "/** Generated by tools/safety-training. Do not edit by hand. */",
        "internal object GeneratedMessageSafetyMlpModel {",
        f"    const val EMBEDDING_DIMENSIONS = {dimensions}",
        f"    const val EMBEDDING_MODEL_ID = \"{_escape(str(embedding.get('model_id') or embedding.get('model_file') or 'embedding_gemma'))}\"",
        f"    const val EMBEDDING_INPUT_MODE = \"{_escape(str(embedding['input_mode']))}\"",
        f"    const val MODEL_ARTIFACT_SHA256 = \"{file_sha256(model_path)}\"",
        f"    const val TRAINING_DATASET_SHA256 = \"{_escape(str(model.get('dataset_sha256', '')))}\"",
        *([f"    const val EMBEDDING_MODEL_SHA256 = \"{_escape(str(embedding.get('model_sha256')))}\""] if embedding.get("model_sha256") else []),
        *([f"    const val EMBEDDING_MODEL_REVISION = \"{_escape(str(embedding.get('model_revision')))}\""] if embedding.get("model_revision") else []),
        "",
        "    data class Head(",
        "        val hiddenSize: Int,",
        "        val hiddenWeights: FloatArray,",
        "        val hiddenBias: FloatArray,",
        "        val outputWeights: FloatArray,",
        "        val outputBias: Float,",
        "        val threshold: Float",
        "    )",
        "",
        "    val byReason: Map<MessageSafetyReason, Head> =",
        "        mapOf(",
    ]

    for label in LABELS:
        entry = model["labels"][label]
        hidden_size = int(entry["hidden_size"])
        hidden_weights = [float(value) for value in entry["hidden_weights"]]
        hidden_bias = [float(value) for value in entry["hidden_bias"]]
        output_weights = [float(value) for value in entry["output_weights"]]
        if len(hidden_weights) != dimensions * hidden_size:
            raise ValueError(
                f"{label} has {len(hidden_weights)} hidden weights; expected {dimensions * hidden_size}"
            )
        if len(hidden_bias) != hidden_size:
            raise ValueError(f"{label} has {len(hidden_bias)} hidden biases; expected {hidden_size}")
        if len(output_weights) != hidden_size:
            raise ValueError(f"{label} has {len(output_weights)} output weights; expected {hidden_size}")

        lines.extend(
            [
                f"            MessageSafetyReason.{_REASON[label]} to",
                "                Head(",
                f"                    hiddenSize = {hidden_size},",
                "                    hiddenWeights =",
                "                        floatArrayOf(",
            ]
        )
        _append_float_array(lines, hidden_weights, indent="                            ")
        lines.extend(
            [
                "                        ),",
                "                    hiddenBias =",
                "                        floatArrayOf(",
            ]
        )
        _append_float_array(lines, hidden_bias, indent="                            ")
        lines.extend(
            [
                "                        ),",
                "                    outputWeights =",
                "                        floatArrayOf(",
            ]
        )
        _append_float_array(lines, output_weights, indent="                            ")
        lines.extend(
            [
                "                        ),",
                f"                    outputBias = {_float(float(entry['output_bias']))},",
                f"                    threshold = {_float(float(entry['threshold']))}",
                "                ),",
            ]
        )

    lines.extend(["        )", "}", ""])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def _append_float_array(lines: list[str], values: list[float], *, indent: str) -> None:
    for chunk_start in range(0, len(values), 6):
        chunk = values[chunk_start : chunk_start + 6]
        suffix = "," if chunk_start + 6 < len(values) else ""
        lines.append(indent + ", ".join(_float(value) for value in chunk) + suffix)


def _float(value: float) -> str:
    return f"{value:.9g}f"


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
